# Tensorflow basics for deep learning
## topics covered
* Initializing and casting
* Indexing
* Maths Operations
* Linear Algebra Operations
* Common tensorflow functions
* Ragged tenosrs
* Sparse Tensors
* String Tensors 
* Variables

In [1]:
import tensorflow as tf


### Creating tensors

In [2]:
# creating a zero_d tensor

tensor_zero_d =tf.constant(6)

#creating a one dimensional tensor

tensor_one_d=tf.constant([2,4,6])

#creating a 2d tensor

tensor_two_d=tf.constant([
    [1,2,4],
    [4,5,6],
    [7,8,9]
])
# creating a three d tensor
tensor_three_d=tf.constant([
    [[1,3,4],
     [1,4,2]]
    
])
# creating a four d tensor
tensor_three_d.ndim


3

#### casting tensors

In [3]:
casted_tensor_one_d=tf.cast(tensor_one_d,dtype=tf.int16)
casted_tensor_one_d

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([2, 4, 6], dtype=int16)>

#### fill method used to create tensors

In [4]:
# creates a tensor and fill it with a scalar value.first argument takes the shape of the tensor
# the second argument takes the scalar value that will poputlate the tensor
# tf.ones(shape) similar to tf.fill but rather fills the tensor with the scalar value '1'
fill_tensor=tf.fill([3,2,2],9,name=None)

#tf.ones_like() gives a tensor of similar shape to the input tensor but fills it with ones
fill_tensor_ones=tf.ones_like(fill_tensor)
fill_tensor_ones

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])>

#### creating random tensors

In [5]:
#tf.random.normal -creates a random tensor based off of normal distribution
# tf.random.unifrom - creates a  random tensor based off of uniform distribution

random_normal=tf.random.normal([4,2],
                               mean=0.0,
                               stddev=1.0,
                               dtype=tf.float32,
                               seed=42,
                               name=None)

random_uniform=tf.random.uniform(
    [3,2,2],
    minval=5,
    maxval=40,
    dtype=tf.int32,
    name=None
)
random_uniform

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 8, 19],
        [17, 19]],

       [[ 9, 11],
        [39,  6]],

       [[34, 39],
        [21, 27]]])>

#### indexing


In [6]:
#getting the first column from random_uniform

ru1=random_uniform[:,:,0]

# fetch the first column of the last element
rulast=random_uniform[2,:,0]
rulast

# get the first column of the second element
col2=random_uniform[1,0,:]
col2


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 9, 11])>

# Squeezing and unsqueezing tensor dimensions in tensorflow

In [7]:
# unsqueezing the dimension of random_uniform

random_uniform_squeeze=tf.squeeze(random_uniform)
print(random_uniform_squeeze.shape)

# unsqueezing random_uniform
random_uniform4d=tf.expand_dims(random_uniform,axis=0)
print(random_uniform4d.shape,tf.rank(random_uniform4d))

#squeezing added dimension
random_uniform4d_squeeze=tf.squeeze(random_uniform4d,axis=0)
tf.rank(random_uniform_squeeze),random_uniform_squeeze.shape

(3, 2, 2)
(1, 3, 2, 2) tf.Tensor(4, shape=(), dtype=int32)


(<tf.Tensor: shape=(), dtype=int32, numpy=3>, TensorShape([3, 2, 2]))